# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  
  setup:
    cmds:
      - shards install

  test:
    cmds:
      - crystal spec